[package]
name = "dynamodb-code-examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
  "David Souther <davidsouther@gmail.com>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-dynamodb = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = [
  "client-hyper",
  "rustls",
  "rt-tokio",
] }
aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = [
  "rt-tokio",
] }
aws-smithy-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
axum = "0.5.16"
http = "0.2.5"
futures = "0.3"
log = "0.4.17"
rand = "0.8.3"
sdk-examples-test-utils = { path = "../../test-utils" }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+0_22"] }
clap = { version = "4.2.1", features = ["derive"] }
tracing = "0.1"
thiserror = "1.0"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.8"
tower-http = { version = "0.3.0", features = ["cors"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
