[package]
name = "telephone-code-example"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.0.1"
aws-sdk-polly = "1.2.0"
aws-sdk-s3 = "1.2.0"
aws-sdk-transcribe = "1.2.0"
aws-smithy-types = { features = ["rt-tokio"],  version = "1.0.1"}
anyhow = "1"
tokio = { version = "1.20.1", features = ["full"] }
bytes = "1"
reqwest = "0.11.4"
serde_json = "1.0"
clap = { version = "~4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
