[package]
name = "step-function-code-examples"
version = "0.1.0"
authors = ["Daniele Frasca <https://github.com/ymwjbxxq/>"]
edition = "2021"

[dependencies]
aws-config = { features = ["behavior-version-latest"], version = "1.0.1"}
aws-sdk-sfn = "1.2.0"
tokio = { version = "1.20.1", features = ["full"] }
clap = { version = "~4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
