[package]
name = "sdk-examples-test-utils"
version = "0.1.0"
authors = [
  "David Souther <dpsouth@amazon.com>",
]
edition = "2021"

[workspace]

[dependencies]
aws-config = "1.0.1"
aws-smithy-types = "1.0.1"
aws-smithy-runtime = { features = ["test-util"],  version = "1.0.1"}
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next"}
http = "0.2"
tokio = "1.33.0"

[lib]
path="src/mod.rs"