[package]
name = "greengrassv2-code-examples"
version = "0.1.0"
authors = ["Aaron Tsui <aaron.tsui@outlook.com>"]
edition = "2021"

[dependencies]
aws-config = { features = ["behavior-version-latest"], version = "1.0.1"}
aws-sdk-greengrassv2 = "1.2.0"
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
tokio = { version = "1", features = ["full"] }
clap = { version = "~4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
