- name: lang/all-languages
  color: "663399"
  description: "This issue relates to all AWS SDKs"
  from_name: "All SDK languages"
- name: lang/cpp
  color: "663399"
  description: "This issue relates to the AWS SDK for C++"
  from_name: "C++"
- name: lang/dotnet-v3
  color: "663399"
  description: "This issue relates to the AWS SDK for .NET V3"
  from_name: ".NET"
- name: lang/go-v1
  color: "663399"
  description: "This issue relates to the AWS SDK for Go V1"
- name: lang/go-v2
  color: "663399"
  description: "This issue relates to the AWS SDK for Go V2"
  from_name: "Go"
- name: lang/java-v1
  color: "663399"
  description: "This issue relates to the AWS SDK for Java V1"
- name: lang/java-v2
  color: "663399"
  description: "This issue relates to the AWS SDK for Java V2"
  from_name: "Java"
- name: lang/javascript-v2
  color: "663399"
  description: "This issue relates to the AWS SDK for Javascript V2"
- name: lang/javascript-v3
  color: "663399"
  from_name: "Javascript"
  description: "This issue relates to the AWS SDK for Javascript V3"
- name: lang/kotlin
  color: "663399"
  from_name: "Kotlin"
  description: "This issue relates to the AWS SDK for Kotlin"
- name: lang/php
  color: "663399"
  from_name: "PHP"
  description: "This issue relates to the AWS SDK for PHP"
- name: lang/python
  color: "663399"
  from_name: "Python"
  description: "This issue relates to the AWS SDK for Python (boto3)"
- name: lang/ruby
  color: "663399"
  from_name: "Ruby"
  description: "This issue relates to the AWS SDK for Ruby"
- name: lang/rust
  color: "663399"
  from_name: "Rust"
  description: "This issue relates to the AWS SDK for Rust (Preview)"
- name: lang/swift
  color: "663399"
  from_name: "swift"
  description: "This issue relates to the AWS SDK for Swift"
- name: lang/typescript
  color: "663399"
  from_name: "TypeScript"
  description: "This issue relates to the AWS SDK for Typescript"
- name: lang/shell
  color: "663399"
  from_name: "shell script"
  description: "Tools written in bash/sh"
- name: tool/cli
  description: "Relates to the AWS CLI"
  from_name: "CLI"
  color: "663399"
- name: tool/cdk
  color: "663399"
  description: "Relates to the AWS Cloud Development Kit (CDK)"
  from_name: "CDK"
- name: tool/cloudformation
  description: "Relates to CloudFormation templates"
  color: "663399"
  from_name: "CloudFormation"

- name: status/needs-code-review
  color: "008080"
  description: "This work needs code review"
  from_name: "Ready for review"
- name: status/needs-text-review
  color: "008080"
  description: "This work needs editorial (text) review"
  from_name: "Editorial"
- name: status/needs-testing-review
  color: "008080"
  description: "This work needs its test reviewed"
  from_name: "Ready for test review"

- name: status/has-code-review
  color: "7FFF00"
  description: "Code review complete"
- name: status/has-text-review
  color: "7FFF00"
  description: "Text review complete"
- name: status/has-testing-review
  color: "7FFF00"
  description: "Testing review complete"

- name: status/in-progress
  color: "008080"
  description: "This work is currently in progress"
  from_name: "Work in progress"
- name: status/ready-to-merge
  color: "7FFF00"
  description: "This work is READY TO MERGE"
  from_name: "Ready for merge"
- name: status/back-to-author
  color: "00FFFF"
  from_name: "Back to author"
  description: "This work needs further work (other)"
- name: status/needs-input
  color: "00FFFF"
  description: "This work needs input from the reporter"
  from_name: "needs input"
- name: status/needs-research
  color: "00FFFF"
  description: "This work needs research by the resolver"
  from_name: "needs research"
- name: status/future-release
  color: "00FFFF"
  description: "Hold for merge until after release"
  from_name: "Future release"

- name: status/duplicate
  color: "00FFFF"
  description: "This is a duplicate"
  from_name: "duplicate"
- name: status/stale
  color: "00FFFF"
  description: "This is stale"
- name: status/icebox
  color: "008080"
  description: "This is old, but should not be closed"
- name: status/ready
  color: "008080"
  description: "Ready for work to be done"
  from_name: "Sprint ready"

- name: type/code-example-request
  color: "d8bfd8"
  description: "Request for a code sample"
  from_name: "code example request"
- name: type/cross-service
  color: "d8bfd8"
  description: "This work is about a cross-service sample"
  from_name: "Cross-service example"
- name: type/mvp
  color: "d8bfd8"
  description: "This work is about an MVP sample"
- name: type/dependency
  color: "d8bfd8"
  description: "This work is about a dependency"
  from_name: "dependencies"
- name: type/chore
  color: "d8bfd8"
  description: "This work is about a chore"
- name: type/bug
  color: "d8bfd8"
  description: "A bug in an existing code sample"
  from_name: "bug"
- name: type/enhancement
  color: "d8bfd8"
  description: "An enhancement to an existing code sample"
  from_name: "enhancement"
- name: type/epic
  color: "d8bfd8"
  description: "This is an Epic"
  from_name: "epic"
- name: type/task
  color: "d8bfd8"
  description: "This work is a task that needs to be done"
  from_name: "task"
- name: type/user-story
  color: "d8bfd8"
  description: "This is a user story"
  from_name: "user story"
- name: type/sos
  color: "d8bfd8"
  description: "Internal: Relates to Scouring of the Services"
  from_name: "SoS"
- name: type/github-settings
  color: "5AF8F9"
  description: "This affects GitHub settings"
  from_name: "github-settings"

- name: priority/high
  color: "FF0000"
  description: "High Priority"
  from_name: "High"
- name: priority/medium
  color: "FF4500"
  description: "Medium Priority"
  from_name: "Medium"
- name: priority/low
  color: "FF8C00"
  description: "Low priority"
  from_name: "Low"
- name: priority/wishlist
  color: "f5deb3"
  description: "It'd be nice to have this"
