# Labels for keeping the merge button red
- name: On Call Review needed
  from_name: status/on-call-review-needed
  color: "AD1C21"
  description: "This work needs an on-call review"
- name: Text Review needed
  from_name: status/text-review-needed
  color: "AD1C21"
  description: "This work needs editorial (text) review"

# Labels to affirm the merge button can be green
- name: On Call Review complete
  from_name: status/on-call-review-complete
  color: "1FC058"
  description: "On call review complete"
- name: Text Review complete
  from_name: status/text-review-complete
  color: "1FC058"
  description: "Text review complete"
- name: Text Review not needed
  from_name: status/no-text-review-needed
  color: "1FC058"
  description: "This contains no text which needs review"

# Labels for tracking statistics and history
- name: MVP
  color: f5f7f9
  description: "A Minimum Viable Product example to show the bare bones of how to use a service via an SDK."
- name: Workflow
  color: f5f7f9
  description: "A simple code example to show how certain tasks can be accomplished using several services and SDKs."
- name: Application
  color: f5f7f9
  description: "An example with multiple AWS Services and SDKs to show how to build a complete, working application."
- name: Bug
  color: f5f7f9
  description: "A general update to the code base for bug fixes, language clarification, typos, etc."

- name: Scout
  color: f5f7f9
  description: "An example which other languages will use for reference later on."
- name: Follow
  color: f5f7f9
  description: "After Scouts, more languages are added to examples as Follows."

- name: C++
  from_name: lang/cpp
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for C++"
- name: DotNet-v3
  from_name: lang/dotnet-v3
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for .NET V3"
- name: Go-v1
  from_name: lang/go-v1
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Go V1"
- name: Go-v2
  from_name: lang/go-v2
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Go V2"
- name: Java-v1
  from_name: lang/java-v1
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Java V1"
- name: Java-v2
  from_name: lang/java-v2
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Java V2"
- name: Javascript-v2
  from_name: lang/javascript-v2
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Javascript V2"
- name: Javascript-v3
  from_name: lang/javascript-v3
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Javascript V3"
- name: Kotlin
  from_name: lang/kotlin
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Kotlin"
- name: PHP
  from_name: lang/php
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for PHP"
- name: Python
  from_name: lang/python
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Python (boto3)"
- name: Ruby
  from_name: lang/ruby
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Ruby"
- name: Rust
  from_name: lang/rust
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Rust (Preview)"
- name: Swift
  from_name: lang/swift
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Swift"
- name: Typescript
  from_name: lang/typescript
  color: "f5f7f9"
  description: "This issue relates to the AWS SDK for Typescript"
- name: Shell
  from_name: lang/shell
  color: "f5f7f9"
  description: "Tools written in bash/sh"

- name: CLI
  from_name: tool/cli
  description: "Relates to the AWS CLI"
  color: "f5f7f9"
- name: CDK
  from_name: tool/cdk
  color: "f5f7f9"
  description: "Relates to the AWS Cloud Development Kit (CDK)"
- name: CloudFormation
  from_name: tool/cloudformation
  description: "Relates to CloudFormation templates"
  color: "f5f7f9"
- name: Testing
  from_name: tool/integration-testing
  description: "Relates to integration testing"
  color: "f5f7f9"
- name: GitHub settings
  from_name: type/github-settings
  color: "f5f7f9"
  description: "This affects GitHub settings"

# Labels to visually distinguish special types of issues
- name: Urgent
  color: "00FFFF"
  description: "Very important and needs attention"
- name: Epic
  from_name: size/epic
  color: "d8bfd8"
  description: "Contains many smaller pieces to work on separately"
- name: Tracker
  from_name: type/tracking
  color: "a0d0fa"
  description: "Similar to an Epic, but used to track a single individual's multi-part issues."
