[package]
name = "sdk-examples-test-utils"
version = "0.1.0"
authors = [
  "David Souther <dpsouth@amazon.com>",
]
edition = "2021"

[workspace]

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = [
  "test-util",
] }
aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main"}
http = "0.2"

[lib]
path="src/mod.rs"