db_name: auroraappdb
engine: mysql
host: your-host
port: 3306
cluster:
  cluster_name: doc-example-aurora-app-cluster
  DBClusterArn: arn:aws:rds:us-east-1:123456789100:cluster:doc-example-aurora-app-docexampleauroraappcluster
secret:
  ARN: arn:aws:secretsmanager:us-east-1:123456789100:secret:docexampleauroraappsecret
