[package]
name = "rest_ses"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rest_ses"

[dependencies]
actix-web = "4"
actix-web-prom = "0.6.0"
aws-config = "1.0.1"
aws-sdk-cloudwatchlogs = "1.2.0"
aws-sdk-rdsdata = "1.2.0"
aws-sdk-ses = "1.2.0"
aws-smithy-types = "1.0.1"
aws-smithy-runtime = "1.0.1"
chrono = { version = "0.4.22", default-features = false, features = [
    "clock",
    "serde",
] }
color-eyre = "0.6.2"
config = "0.13.2"
derive_more = "0.99.17"
futures = "0.3.24"
http = "0.2.8"
mail-builder = "0.2.5"
reqwest = "0.11.12"
sdk-examples-test-utils = { path = "../../test-utils" }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.86"
thiserror = "1.0.37"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-actix-web = "0.7.3"
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
uuid = { version = "1.2.1", features = ["v4", "serde"] }
xlsxwriter = "0.6.0"

[dev-dependencies]
aws-smithy-runtime = "1.0.1"
fake = { version = "2.5.0", features = ["uuid"] }
once_cell = "1.15.0"
rand = "0.8.5"
wiremock = "0.5.15"
