[package]
name = "example-lambda-calculator"
version = "0.1.0"
authors = [
  "David Souther <davidsouther+amazon@>",
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-ec2 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-lambda = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
lambda_runtime = "0.8.0"
clap = { version = "4.2.1", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "json"] }
time = "0.3"
tracing = "0.1.37"
serde_json = "1.0.94"
anyhow = "1.0.71"
serde = "1.0.164"

