[package]
name = "secretsmanager-code-examples"
version = "0.1.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2021"
description = "Example usage of the SecretManager service"

[dependencies]
aws-config = { features = ["behavior-version-latest"], version = "1.0.1"}
aws-sdk-secretsmanager = "1.2.0"
tokio = { version = "1.20.1", features = ["full"] }
clap = { version = "~4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
