[package]
name = "testing-examples"
version = "0.1.0"
authors = [
  "John Disanti <jdisanti@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2021"

# snippet-start:[testing.rust.Cargo.toml]
[dependencies]
async-trait = "0.1.51"
aws-config = { features = ["behavior-version-latest"], version = "1.0.1"}
aws-credential-types = { features = [ "hardcoded-credentials", ],  version = "1.0.1"}
aws-sdk-s3 = "1.2.0"
aws-smithy-types = "1.0.1"
aws-smithy-runtime = { features = ["test-util"],  version = "1.0.1"}
aws-smithy-runtime-api = { features = ["test-util"],  version = "1.0.1"}
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
clap = { version = "~4.4", features = ["derive"] }
http = "0.2.9"
mockall = "0.11.4"
serde_json = "1"
tokio = { version = "1.20.1", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
# snippet-end:[testing.rust.Cargo.toml]

[[bin]]
name = "main"
path = "src/main.rs"
