[package]
name = "photo_asset_management_integration"
version = "0.1.0"
edition = "2021"

[workspace]


[dependencies]
aws-config = "1.0.1"
aws-sdk-dynamodb = "1.2.0"
aws-sdk-rekognition = "1.2.0"
photo_asset_management = { path = "../"}
tokio = { version = "1.27.0", features = ["macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
