---
name: Label Checker
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check On Call Review labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          all_of: On Call Review complete
          none_of: On Call Review needed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_text_labels:
    name: Check Text labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: Text Review complete,Text Review not needed
          none_of: Text Review needed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
