# Run Python checkin script on push or pull request
name: Snippet & Repo Validation Checks

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 #install the python needed
      - name: Install dependencies
        run: >-
          python3 -m pip install -r .tools/base_requirements.txt
      - name: Lint metadata files
        run: >-
          yamllint --format standard -c .tools/validation/.yamllint.yaml .doc_gen/metadata .doc_gen/metadata/curated
      - name: Validate metadata and repo
        run: >-
          python3 .tools/validation/validate.py --doc-gen .doc_gen
